[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "7hhqzFD9HZRcdnLcFqjeCYtLYyKDZacJ5VSnHAH7uyR7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/avy/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
